### PR TITLE
Fix of multiplying connections

### LINKED ISSUE #824: Mergin API call for billing called multiple times
on sign in there is multiple call of `/v1/plan` endpoint

### PR DESCRIPTION
**Pull request by sklencar**
Input Purchasing backend is created at the very beginning. However it is cleaned and recreated once again after merginStatus has been changed - also called at the beginning while pinging mergin and getting its status. Each call of `createBackend` resets `mBackend` pointer and creates also new connections to already existing mMerginApi connections and new connections to reseted mBackend pointer. The call of the function caused multiplying of connections and therefore calling some (even server) functions multiple times.

This is simple fix of disconnecting existing connection on clean.  
closes #824

### CODE REVIEW

File: app/purchasing.cpp [hunk 1]
```diff
@@ -398,6 +398,22 @@ void Purchasing::onFetchPurchasingPlansFinished()
...
+    disconnect( mBackend.get(), &PurchasingBackend::transactionCreationSucceeded, this, &Purchasing::onTransactionCreationSucceeded );
+    disconnect( mBackend.get(), &PurchasingBackend::transactionCreationFailed, this, &Purchasing::onTransactionCreationFailed );
+  }
+
+  if ( mMerginApi )
+  {
+    disconnect( mMerginApi, &MerginApi::apiRootChanged, this, &Purchasing::onMerginServerChanged );
+    disconnect( mMerginApi, &MerginApi::apiSupportsSubscriptionsChanged, this, &Purchasing::onMerginServerChanged );
+    disconnect( mMerginApi, &MerginApi::apiVersionStatusChanged, this, &Purchasing::onMerginServerStatusChanged );
+  }
```
Comment (wonder-sk) [inline app/purchasing.cpp:415]: rather than connecting to MerginApi in createBackend() and disconnecting later, it is better to connect in the constructor once and then never disconnect.

File: app/purchasing.cpp [hunk 2]
```diff
@@ -398,6 +398,22 @@ void Purchasing::onFetchPurchasingPlansFinished()
...
 void Purchasing::clean()
 {
+  if ( mBackend )
+  {
+    disconnect( mBackend.get(), &PurchasingBackend::planRegistrationSucceeded, this, &Purchasing::onPlanRegistrationSucceeded );
+    disconnect( mBackend.get(), &PurchasingBackend::planRegistrationFailed, this, &Purchasing::onPlanRegistrationFailed );
+
+    disconnect( mBackend.get(), &PurchasingBackend::transactionCreationSucceeded, this, &Purchasing::onTransactionCreationSucceeded );
+    disconnect( mBackend.get(), &PurchasingBackend::transactionCreationFailed, this, &Purchasing::onTransactionCreationFailed );
+  }
```
Comment (wonder-sk) [inline app/purchasing.cpp:408]: If we delete mBackend, all connections would be removed, so we should not need to disconnect them explicitly
