### PR TITLE
Do not forget pending status of a project

### LINKED ISSUE #371: Sync progress of a project temporarily lost
It seems pending mode of a project in the mergin project list is always forgotten after refresh
Write tests.

### LINKED ISSUE #565: When switching apps, Input loses the status of the project
When I am in a project and switch to another app, after I come back, Input has already shut down the project and takes me to another screen.

### LINKED ISSUE #582: When uploading large files get interrupted, the sync will not resume
`server replied: BAD REQUEST. Another process is running. Please try later.`

To reproduce:
download a simple project, then add a bunch of images (so it's a couple of MB to upload) - and while uploading, try to break it somehow e.g. jump out of projects list and back, out of the application and back etc - and see if you would be allowed to press sync button again instead of getting progress bar there with a cancel button

### PR DESCRIPTION
**Pull request by sklencar**
List of projects has been whole replaced regardless pending state of some of the projects.

closes #582 closes #565 closes #371

### CODE REVIEW

File: app/merginprojectmodel.cpp [hunk 1]
```diff
@@ -90,25 +90,38 @@ int MerginProjectModel::rowCount( const QModelIndex &parent ) const
...
-    LocalProjectInfo localProject = mLocalProjects.projectFromMerginName( entry.projectNamespace, entry.projectName );
-    if ( localProject.isValid() )
+    QString fullProjectName = MerginApi::getFullProjectName( entry.projectNamespace, entry.projectName );
+    std::shared_ptr<MerginProject> currentMerginProject = findProjectByFullName( fullProjectName );
+    if ( currentMerginProject && currentMerginProject->pending )
     {
-      project->projectDir = localProject.projectDir;
-      project->status = localProject.status;
-      // TODO: what else to copy?
+      newProjects << currentMerginProject;
```
Comment (wonder-sk) [inline app/merginprojectmodel.cpp]: Could you please add a comment why we are doing this? I guess we don't want to loose the "pending" and "progress" information, anything else?

I am wondering if it would not be cleaner to still make new MerginProject like before, just have these two attributes (pending+progress) copied from the old project - just like how we copy stuff from mLocalProjects. This way it would be more explicit why we do it... what do you think?

Comment (sklencar) [reply app/merginprojectmodel.cpp]: Don't have preferences. The other solutions would bring an update of server version, if it would have increased in a meanwhile..or even deleted (not be present anymore). So +1.

However, just realised the issue is more complex, so WIP

File: app/merginprojectmodel.cpp [hunk 2]
```diff
@@ -107,8 +109,17 @@ void MerginProjectModel::resetProjects( const MerginProjectList &merginProjects
       // TODO: what else to copy?
     }
 
+    if ( pendingProjects.contains( fullProjectName ) )
+    {
+
+      TransactionStatus projectTransaction = pendingProjects.value( fullProjectName );
+      project->progress = projectTransaction.transferedSize / projectTransaction.totalSize;
+      project->pending = project->progress >= 0;
```
Comment (wonder-sk) [inline app/merginprojectmodel.cpp]: shouldn't this be `project->pending = true` if it is listed within pendingProjects ?

File: app/merginprojectmodel.cpp [hunk 3]
```diff
@@ -150,6 +174,8 @@ void MerginProjectModel::syncProjectStatusChanged( const QString &projectFullNam
   project->pending = progress >= 0;
   project->progress = progress >= 0 ? progress : 0;
 
+  //if project->pending()
+
```
Comment (wonder-sk) [inline app/merginprojectmodel.cpp]: some unwanted update?

File: app/merginprojectmodel.h [hunk 4]
```diff
@@ -82,8 +83,10 @@ class MerginProjectModel: public QAbstractListModel
   private:
 
     int findProjectIndex( const QString &projectFullName );
+    std::shared_ptr<MerginProject> findProjectByFullName( const QString &projectFullName );
 
     ProjectList mMerginProjects;
+    ProjectList mMerginPendingProjects;
```
Comment (wonder-sk) [inline app/merginprojectmodel.h]: unused?

File: app/merginprojectmodel.h [hunk 5]
```diff
@@ -82,8 +83,10 @@ class MerginProjectModel: public QAbstractListModel
   private:
 
     int findProjectIndex( const QString &projectFullName );
+    std::shared_ptr<MerginProject> findProjectByFullName( const QString &projectFullName );
```
Comment (wonder-sk) [inline app/merginprojectmodel.h]: this function does not seem to exist?
