### PR TITLE
Forms refactoring

### LINKED ISSUE #1035: Refactor form-related models
There are several models linked together making things quite complex - and buggy in some more advanced scenarios, e.g. when using conditional visibility. It would be good to simplify the whole approach - maybe something like this:

- do not link models together - e.g. the dreaded QgsQuickSubModel
- use just simple list models (not hierarchical)
- have one central controller class for all the form logic to avoid spaghetti of signals
- remove QgsQuickAttributeModel if possible - if we don't need that item model then let's keep the logic in the central controller

image

### LINKED ISSUE #1233: Input creates tab for each widget in form
Probably related to #1035. 

@wonder-sk finally found reproducible scenario for this bug.

To reproduce:
 - open project `lutraconsulting/test_forms`
 - open feature form
 - open different project that does not have multiple tabs

Experienced:
 - you will see tabs created for all widgets

Sometimes application crashes when this bug happens.
I could reproduce this issue on all platforms

image

### PR DESCRIPTION
**Pull request by PeterPetrik**
- This PR removed the QgsQuick models for form attribute tables (submodel, attributemodel, featureformmodel,...) and recreates them in the new style with the attribute form controller. The controller owns all the data and the form/tab models are just the slim wrappers. 
- Also the preview form was extracted from the __loader to the preview form controller. 
- Remember attributes functionality was extracted to the remember attributes controller. 
- Copied the qgsquick tests to the input repository and added them to CI

fix #1233
fix #1035

### CODE REVIEW

**Comment by saberraz** [comment]
Woohoo, looking forward to no more random crashes!

File: qgsquick/from_qgis/attributes/qgsquickattributedata.h [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+    void setVisible( bool visible );
+
+    QUuid id() const;
+
+    QgsExpression visibilityExpression() const;
+
+  private:
+    const QUuid mId;
+    const QString mName;
+    const QVector<QUuid> &mFormItems;
```
Comment (wonder-sk) [inline qgsquick/from_qgis/attributes/qgsquickattributedata.h:130]: should not be ref

File: qgsquick/from_qgis/attributes/qgsquickattributecontroller.cpp [hunk 2]
```diff
@@ -0,0 +1,533 @@
...
+          fieldUuid,
+          parentTab,
+          QgsQuickFormItem::Field,
+          layer->attributeDisplayName( fieldIndex ),
+          !layer->editFormConfig().readOnly( fieldIndex ),
+          layer->editorWidgetSetup( fieldIndex ),
+          fieldIndex,
+          field.constraints(),
+          parentVisibilityExpressions // field doesn't have visibility expression itself
+        );
```
Comment (wonder-sk) [inline qgsquick/from_qgis/attributes/qgsquickattributecontroller.cpp:190]: looks like bug

File: qgsquick/from_qgis/attributes/qgsquickattributeformmodel.cpp [hunk 3]
```diff
@@ -14,80 +14,145 @@
...
+  }
 }
 
-void QgsQuickAttributeFormModel::save()
+void QgsQuickAttributeFormModel::onFormDataChanged( const QUuid id )
 {
-  mSourceModel->save();
+  const int row = mData.indexOf( id );
+  Q_ASSERT( row > 0 );
+  const QModelIndex index = createIndex( row, 0 );
```
Comment (wonder-sk) [inline qgsquick/from_qgis/attributes/qgsquickattributeformmodel.cpp:90]: should use index(...) instead of createIndex(...) here

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+/**
+ * \ingroup quick
+ *
+ * This is implementation of the controller between QgsQuickAttribute*Model
+ * and the QML's QgsQuick.FeatureForm. It is responsible for creation of the
+ * models, and CRUD management between QgsFeature and the form. It connects
+ * the QgsFeature Fields on the backend side and the QML widgets on the user side
+ *
+ * Remember values functionality is done by QgsQuickRememberAttributes controller.
+ * Preview forms are not supported by this class.
```
Comment (wonder-sk) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:52]: "Preview forms are not supported by this class."  -- I would leave this comment out

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h [hunk 5]
```diff
@@ -0,0 +1,184 @@
...
+
+    //! Returns TRUE if all soft constraints defined on fields are satisfied with the current attribute values
+    Q_PROPERTY( bool constraintsSoftValid READ constraintsSoftValid NOTIFY constraintsSoftValidChanged )
+
+  public:
+    QgsQuickAttributeController( QObject *parent = nullptr );
+    ~QgsQuickAttributeController() override;
+
+    //! Restore clean/initial state: no layer, no feature!
+    Q_INVOKABLE void forceClean();
```
Comment (wonder-sk) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:89]: rename to reset() ?

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h [hunk 6]
```diff
@@ -0,0 +1,184 @@
...
+
+    //! Gets current featureLayerPair
+    QgsQuickFeatureLayerPair featureLayerPair() const;
+    //! Sets current featureLayerPair
+    void setFeatureLayerPair( const QgsQuickFeatureLayerPair &pair );
+
+    bool constraintsHardValid() const;
+    bool constraintsSoftValid() const;
+    bool hasTabs() const;
+    bool hasAnyChanges();
```
Comment (wonder-sk) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:99]: should be const as well?

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h [hunk 7]
```diff
@@ -0,0 +1,184 @@
...
+class QUICK_EXPORT QgsQuickAttributeController : public QObject
+{
+    Q_OBJECT
+
+    /**
+     * QgsQuickFeatureLayerPair for the model. Input for attributes model.
+     */
+    Q_PROPERTY( QgsQuickFeatureLayerPair featureLayerPair READ featureLayerPair WRITE setFeatureLayerPair NOTIFY featureLayerPairChanged )
+
+    // this is newer nullprt
```
Comment (wonder-sk) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:67]:
```suggestion
    // this is never nullptr (a form with no tabs will be parsed as having a single tab)
```

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h [hunk 8]
```diff
@@ -0,0 +1,184 @@
...
+    Q_PROPERTY( QgsQuickAttributeTabProxyModel *attributeTabProxyModel READ attributeTabProxyModel  NOTIFY attributeTabProxyModelChanged )
+
+    //! Returns TRUE if remembering values is allowed
```
Comment (wonder-sk) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:70]: fix comment

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h [hunk 9]
```diff
@@ -0,0 +1,184 @@
...
+    bool constraintsHardValid() const;
+    bool constraintsSoftValid() const;
+    bool hasTabs() const;
+    bool hasAnyChanges();
+
+    QgsQuickAttributeTabProxyModel *attributeTabProxyModel() const;
+    QgsQuickAttributeFormProxyModel *attributeFormProxyModelForTab( int tabRow ) const;
+
+    Q_INVOKABLE bool deleteFeature();
+    Q_INVOKABLE void create();
```
Comment (wonder-sk) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:105]: create cannot fail? (not returning bool?)

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h [hunk 10]
```diff
@@ -0,0 +1,184 @@
...
+    void attributeTabProxyModelChanged();
+    void constraintsHardValidChanged();
+    void constraintsSoftValidChanged();
+    void hasTabsChanged();
+
+    void formDataChanged( QUuid uuid );
+    void tabDataChanged( int id );
+
+    void dataChangedFailed( const QString &msg );
+    void dataChanged( const QString &msg ); // TODO what is this?? feature for signal...
```
Comment (wonder-sk) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:137]: ?

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.cpp [hunk 11]
```diff
@@ -0,0 +1,879 @@
...
+  std::shared_ptr<QgsQuickTabItem> tabItem( new QgsQuickTabItem( tabRow,
+      container->name(),
+      formItemsUuids,
+      expr )
+                                          );
+
+  mTabItems.push_back( tabItem );
+}
+
+void QgsQuickAttributeController::clearAll()
```
Comment (wonder-sk) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.cpp:252]: how is this different from forceClean() ? is it possible to merge them to a single function?

**Review by wonder-sk — COMMENTED** [review]
:clap: :clap: :clap:

File: app/attributepreviewcontroller.h [hunk 12]
```diff
@@ -0,0 +1,160 @@
...
+
+    Q_ENUM( AttributePreviewRoles )
+
+    QHash<int, QByteArray> roleNames() const override;
+    int rowCount( const QModelIndex &parent = QModelIndex() ) const override;
+    QVariant data( const QModelIndex &index, int role = Qt::DisplayRole ) const override;
+
+  private:
+    QVector<QPair<QString, QString>> mItems; //!< pair of name&value
+};
```
[the remark this answers is not in the document]
Comment (PeterPetrik) [reply app/attributepreviewcontroller.h:61]: https://doc.qt.io/qt-5/qstandarditemmodel.html#QStandardItemModel is in QT Gui library which we do not link

File: app/qml/FeaturePanel.qml [hunk 13]
```diff
@@ -58,6 +56,21 @@ Drawer {
...
+      id: rememberAttributesController
+      rememberValuesAllowed: __appSettings.reuseLastEnteredValues
+    }
+
+    QgsQuick.AttributeController {
+      id: attributeController
+      rememberAttributes: rememberAttributesController
+    }
+
+    AttributePreviewController {
```
[the remark this answers is not in the document]
Comment (PeterPetrik) [reply app/qml/FeaturePanel.qml:69]: we call everything "attribute" ... attribute controller, remember attributes ... I would keep it as is

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributetabproxymodel.h [hunk 14]
```diff
@@ -0,0 +1,49 @@
...
+    Q_OBJECT
+  public:
+    QgsQuickAttributeTabProxyModel( QObject *parent = nullptr );
+    ~QgsQuickAttributeTabProxyModel() override;
+
+    bool filterAcceptsRow( int sourceRow, const QModelIndex &sourceParent ) const override;
+
+    // TODO
+    // should be here so in QML when you change the tabproxymodel (e.g. new layer) the function is
+    // called again and model is repopulated
```
[the remark this answers is not in the document]
Comment (PeterPetrik) [reply qgsquick/from_qgis/quickgui/attributes/qgsquickattributetabproxymodel.h:45]: fixed

File: qgsquick/from_qgis/tests/quickgui/testqgsquickattributecontroller.cpp [hunk 15]
```diff
@@ -0,0 +1,182 @@
...
+  QCOMPARE( item1.value(), "one" );
+  QCOMPARE( item1.isVisible(), true );
+
+  const QgsQuickFormItem item2 = controller.formItem( formItems.at( 1 ) );
+  QCOMPARE( item2.name(), "fldint" );
+  QCOMPARE( item2.value(), 1 );
+  QCOMPARE( item2.isVisible(), true );
+}
+
+void TestQgsQuickAttributeController::twoTabs()
```
[the remark this answers is not in the document]
Comment (PeterPetrik) [reply qgsquick/from_qgis/tests/quickgui/testqgsquickattributecontroller.cpp:134]: removed

File: scripts/update_i18n_ts.bash [hunk 16]
```diff
@@ -8,8 +8,8 @@ LUPDATE_PARAMS="-extensions qml,cpp,hpp,h,ui,c -ts"
 
 echo "update_18n_ts.bash QT_DIST_DIR"
 
-if [ ! -f "$DIR/../qgsquick/from_qgis/qgsquickutils.cpp" ]; then
-  echo "Missing $DIR/qgsquick/from_qgis/qgsquickutils.cpp!"
+if [ ! -f "$DIR/../qgsquick/from_qgis/quickgui/qgsquickutils.cpp" ]; then
+  echo "Missing $DIR/qgsquick/from_qgis/quickguiquickgui/qgsquickutils.cpp!"
```
[the remark this answers is not in the document]
Comment (PeterPetrik) [reply scripts/update_i18n_ts.bash:12]: eh...

File: app/qml/FeaturePanel.qml [hunk 17]
```diff
@@ -58,6 +56,21 @@ Drawer {
         PropertyAnimation { properties: "height"; easing.type: Easing.InOutQuad }
     }
 
+    QgsQuick.RememberAttributes {
```
[the remark this answers is not in the document]
Comment (PeterPetrik) [reply app/qml/FeaturePanel.qml:59]: done

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributedata.h [hunk 18]
```diff
@@ -0,0 +1,187 @@
...
+    QVariant originalValue() const;
+
+  private:
+
+    const std::shared_ptr<QgsQuickFormItemData> mItem;
+    const bool mShouldRememberValue;
+    const QVariant mValue;
+};
+
+class QgsQuickFormItemData
```
[the remark this answers is not in the document]
Comment (PeterPetrik) [reply qgsquick/from_qgis/quickgui/attributes/qgsquickattributedata.h:88]: will create formValue and formShouldRememberValue instead of this contruct

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h (hunk 4 above)
Comment (PeterPetrik) [reply qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:52]: ok

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h (hunk 5 above)
Comment (PeterPetrik) [reply qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:89]: ok

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h (hunk 6 above)
Comment (PeterPetrik) [reply qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:99]: ok

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h (hunk 10 above)
Comment (PeterPetrik) [reply qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.h:137]: rm

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.cpp (hunk 11 above)
Comment (PeterPetrik) [reply qgsquick/from_qgis/quickgui/attributes/qgsquickattributecontroller.cpp:252]: this is private function --- helper to clean the internal members. forceClean is public way how to reset

File: scripts/build-qgsquick-android.bash [hunk 19]
```diff
@@ -82,6 +82,6 @@ make -j${CORES} VERBOSE=1
 make install INSTALL_ROOT=${INSTALL_DIR_QGSQUICK}
 
 mkdir -p ${INSTALL_DIR_QGSQUICK}/images
-cp ${SOURCE_DIR}/qgsquick/from_qgis/plugin/qgsquickplugin.h ${INSTALL_DIR_QGSQUICK}/include
-cp -R ${SOURCE_DIR}/qgsquick/from_qgis/images ${INSTALL_DIR_QGSQUICK}/images/QgsQuick
+cp ${SOURCE_DIR}/qgsquick/from_qgis/quickgui/plugin/qgsquickplugin.h ${INSTALL_DIR_QGSQUICK}/include
+cp -R ${SOURCE_DIR}/qgsquick/from_qgis/iquickgui/mages ${INSTALL_DIR_QGSQUICK}/images/QgsQuick
```
Comment (sklencar) [inline scripts/build-qgsquick-android.bash:86]: iquickgui/mages -> quickgui/images

File: qgsquick/from_qgis/quickgui/qgsquickutils.cpp [hunk 20]
```diff
@@ -17,6 +17,7 @@
 #include <QScreen>
 #include <QString>
 #include <QWindow>
+#include <QDebug>
```
Comment (sklencar) [inline qgsquick/from_qgis/quickgui/qgsquickutils.cpp:20]: Seems to be not needed

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributeformproxymodel.h [hunk 21]
```diff
@@ -0,0 +1,42 @@
...
+#include "qgis_quick.h"
+
+class QgsQuickAttributeFormModel;
+
+/**
+ * \ingroup quick
+ *
+ * \note QML Type: AttributeFormProxyModel
+ *
+ * \since QGIS 3.4
```
Comment (sklencar) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributeformproxymodel.h:29]: QGIS 3.20 if would be part of QGIS at all.

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributeformmodel.cpp [hunk 22]
```diff
@@ -0,0 +1,172 @@
...
+{
+  return ( row >= 0 ) && ( row < mData.size() );
+}
+
+QHash<int, QByteArray> QgsQuickAttributeFormModel::roleNames() const
+{
+  QHash<int, QByteArray> roles = QAbstractItemModel::roleNames();
+
+  roles[Type]  = QByteArray( "Type" );
+  roles[Name]  = QByteArray( "Name" );
```
Comment (sklencar) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributeformmodel.cpp:114]: An extra space as well as on line above - not a big deal though

**Review by sklencar — CHANGES_REQUESTED** [review]

File: qgsquick/from_qgis/quickgui/attributes/qgsquickattributeformmodel.cpp [hunk 23]
```diff
@@ -0,0 +1,172 @@
...
+  {
+    case RememberValue:
+    {
+      bool shouldRememberValue = value.toBool();
+      return mController->setFormShouldRememberValue( uuid, shouldRememberValue );
+    }
+
+    case AttributeValue:
+    {
+      bool shouldRememberValue = value.toBool();
```
Comment (sklencar) [inline qgsquick/from_qgis/quickgui/attributes/qgsquickattributeformmodel.cpp:165]: Wrong copy-paste - same as for RememberValue

**Review by sklencar — APPROVED** [review]

File: qgsquick/from_qgis/quickgui/plugin/qgsquickfeatureform.qml [hunk 24]
```diff
@@ -199,38 +173,33 @@ Item {
...
-      model.save()
+      controller.save()
     }
 
     saved()
   }
 
   function hasAnyChanges() {
-    return form.model.attributeModel.hasAnyChanges()
+    return form.controller.hasAnyChanges()
```
Comment (sklencar) [inline qgsquick/from_qgis/quickgui/plugin/qgsquickfeatureform.qml:200]: `return form.controller.hasAnyChanges` since its Q_property now,  not a function.
