### PR TITLE
Addded a proper error msg from the server reply

### LINKED ISSUE #361: Add server error cause in logs
If something fails, mergin server also returns cause of the error as the response body. It is important to log also the server error messages to better diagnose the issues.

### PR DESCRIPTION
**Pull request by sklencar**
closes #361

### CODE REVIEW

File: app/merginapi.cpp [hunk 1]
```diff
@@ -878,14 +899,17 @@ void MerginApi::listProjectsReplyFinished()
...
+    InputUtils::log( r->url().toString(), QStringLiteral( "FAILED - %1" ).arg( message ) );
     mMerginProjects.clear();
 
-    if ( r->errorString() == QLatin1String( "Host requires authentication" ) )
+    int status = r->attribute( QNetworkRequest::HttpStatusCodeAttribute ).toInt();
+    if ( status == 401 || status == 400 )
     {
-      emit authRequested();
+      emit authFailed();
+      emit notify( serverMsg );
```
Comment (wonder-sk) [inline app/merginapi.cpp]: why changing from authRequested to authFailed+notify ? does it fix a a bug?

Comment (sklencar) [reply app/merginapi.cpp]: The code is actually obsolate, will be removed.
