### PR TITLE
Bug/project list order

### LINKED ISSUE #367: Order of projects
Projects in Home tab are currently quite randomly ordered. I would suggest this ordering:
- first projects that are not from mergin (listed without namespace)
- then projects from mergin ("namespace/project"): first ordered by namespace, then in case of the same namespace by project name
- sorting is not case sensitive

Also when a new project is downloaded, it should be placed at the correct place (nowadays it is placed at the bottom).

### PR DESCRIPTION
**Pull request by sklencar**
closes #367

### CODE REVIEW

File: app/projectsmodel.h [hunk 1]
```diff
@@ -88,7 +88,24 @@ class ProjectModel : public QAbstractListModel
 
       bool operator < ( const ProjectFile &str ) const
```
Comment (wonder-sk) [inline app/projectsmodel.h]: can we rename "str" to "other" ? it is common naming scheme for operators and it is easier to follow the code then...

File: app/projectsmodel.h [hunk 2]
```diff
@@ -88,7 +88,24 @@ class ProjectModel : public QAbstractListModel
...
+        if ( !projectNamespace.isEmpty() && str.projectNamespace.isEmpty() )
+        {
+          return false;
+        }
+        if ( projectNamespace.isEmpty() && !str.projectNamespace.isEmpty() )
+        {
+          return true;
+        }
+
+        if ( ( projectNamespace.isEmpty() && str.projectNamespace.isEmpty() ) || projectNamespace.toLower() == str.projectNamespace.toLower() )
```
Comment (wonder-sk) [inline app/projectsmodel.h]: is it necessary to have also the check for isEmpty() here? doesn't the second check cover that too?
