### PR TITLE
Fix of wrong and not connected choosing mapTheme with a record layer

### LINKED ISSUE #535: Switching between survey layers
When I try to switch between two survey layers (e.g. a polygon and point), the capture mode seems to get stuck in one of them. In my case, when I switch from polygon to point, it still thinks I am in polygon mode and keeps asking me to add more vertices to create the polygon.

### PR DESCRIPTION
**Pull request by sklencar**
Refactored code - moved handling of active layer and map theme to cpp code (models)

Travis build config updated due to error.

closes #535

### CODE REVIEW

File: app/mapthemesmodel.cpp [hunk 1]
```diff
@@ -112,3 +112,17 @@ void MapThemesModel::applyTheme( const QString &name )
...
+  int i = 0;
+  for ( QString theme : mMapThemes )
+  {
+    if ( theme == name )
+    {
+      return i;
+    }
+    i++;
+  }
+  return defaultIndex;
```
Comment (wonder-sk) [inline app/mapthemesmodel.cpp]: How about using `mMapThemes.indexOf(name)` ?

File: app/layersmodel.cpp [hunk 2]
```diff
@@ -63,10 +63,31 @@ void LayersModel::reloadLayers()
...
+  return mActiveIndex;
+}
+
+void LayersModel::setActiveIndex( int activeIndex )
+{
+  if ( mActiveIndex != activeIndex )
+  {
+    mActiveIndex = activeIndex;
+  }
+  emit activeIndexChanged();
```
Comment (PeterPetrik) [inline app/layersmodel.cpp]: should we emit only when index is actually changed?

File: app/layersmodel.cpp [hunk 3]
```diff
@@ -63,10 +63,31 @@ void LayersModel::reloadLayers()
...
     endResetModel();
 
-    emit layersChanged();
+    emit layersReloaded();
   }
 }
 
+void LayersModel::updateActiveLayer( const QString &name )
+{
+  int row = rowAccordingName( name, firstNonOnlyReadableLayerIndex() );
```
Comment (PeterPetrik) [inline app/layersmodel.cpp]: firstNonOnlyReadableLayerIndex() ... interesting ... whatabout firstWritableLayerIndex?

File: app/layersmodel.cpp [hunk 4]
```diff
@@ -192,6 +213,11 @@ int LayersModel::firstNonOnlyReadableLayerIndex() const
   return -1;
 }
 
+QgsMapLayer *LayersModel::activeLayer()
+{
+  return mLayers.at( activeIndex() );
```
Comment (PeterPetrik) [inline app/layersmodel.cpp]: https://doc.qt.io/qt-5/qlist.html#at

is activeIndex() always in bounds of the mLayers? if yes, add Q_ASSERT, if not , add a condition to return nullptr

File: app/layersmodel.h [hunk 5]
```diff
@@ -50,6 +51,8 @@ class LayersModel : public QAbstractListModel
     Q_INVOKABLE int noOfEditableLayers() const;
     Q_INVOKABLE int firstNonOnlyReadableLayerIndex() const;
 
+    Q_INVOKABLE QgsMapLayer *activeLayer();
```
Comment (PeterPetrik) [inline app/layersmodel.h]: add docs. could be nullprt? ....

File: app/layersmodel.h [hunk 6]
```diff
@@ -59,16 +62,22 @@ class LayersModel : public QAbstractListModel
...
+    void activeLayerNameChanged( const QString &name );
 
   public slots:
     void reloadLayers(); //when project file changes, reload all layers, etc.
+    void updateActiveLayer( const QString &name );
 
   private:
     QgsProject *mProject;
     QList<QgsMapLayer *> mLayers; // all layers
+    int mActiveIndex;
```
Comment (PeterPetrik) [inline app/layersmodel.h]: add default value (=-1?)

File: app/mapthemesmodel.h [hunk 7]
```diff
@@ -42,6 +43,7 @@ class MapThemesModel : public QAbstractListModel
     Q_INVOKABLE QVariant data( const QModelIndex &index, int role ) const override;
     Q_INVOKABLE QModelIndex index( int row, int column = 0, const QModelIndex &parent = QModelIndex() ) const override;
     Q_INVOKABLE void applyTheme( const QString &name );
+    Q_INVOKABLE int rowAccordingName( QString name, int defaultIndex = -1 ) const;
```
Comment (PeterPetrik) [inline app/mapthemesmodel.h]: I do not understand the name of the function. either replace name or write a docs

File: app/main.cpp [hunk 8]
```diff
@@ -294,23 +295,30 @@ int main( int argc, char *argv[] )
...
-  QObject::connect( &loader, &Loader::projectReloaded, &mtm, &MapThemesModel::reloadMapThemes );
-  QObject::connect( &mtm, &MapThemesModel::reloadLayers, &lm, &LayersModel::reloadLayers );
   QObject::connect( ma.get(), &MerginApi::syncProjectFinished, &pm, &ProjectModel::addProject );
   QObject::connect( ma.get(), &MerginApi::listProjectsFinished, &mpm, &MerginProjectModel::resetProjects );
   QObject::connect( ma.get(), &MerginApi::syncProjectStatusChanged, &mpm, &MerginProjectModel::syncProjectStatusChanged );
   QObject::connect( ma.get(), &MerginApi::reloadProject, &loader, &Loader::reloadProject );
 
+  QObject::connect( &loader, &Loader::projectReloaded, &mtm, &MapThemesModel::reloadMapThemes );
+  QObject::connect( &mtm, &MapThemesModel::mapThemesReloaded, &as, &AppSettings::reloadDefaultMapTheme );
+  QObject::connect( &as, &AppSettings::reloadDefaultMapThemeSignal, &mtm, &MapThemesModel::updateMapTheme );
```
Comment (PeterPetrik) [inline app/main.cpp]: you do not need to name `reloadDefaultMapThemeSignal` with signal suffix

File: app/main.cpp [hunk 9]
```diff
@@ -294,23 +295,30 @@ int main( int argc, char *argv[] )
...
+  QObject::connect( &mtm, &MapThemesModel::mapThemeChanged, &as, &AppSettings::setDefaultMapTheme );
+  QObject::connect( &mtm, &MapThemesModel::mapThemeChanged, &lm, &LayersModel::reloadLayers );
```
Comment (PeterPetrik) [inline app/main.cpp]: if you change mapThemeChanged you need to reload all layers?

File: app/main.cpp [hunk 10]
```diff
@@ -294,23 +295,30 @@ int main( int argc, char *argv[] )
...
+
+  QObject::connect( &lm, &LayersModel::layersReloaded, &as, &AppSettings::reloadDefaultLayer );
+  QObject::connect( &as, &AppSettings::reloadDefaultLayerSignal, &lm, &LayersModel::updateActiveLayer );
```
Comment (PeterPetrik) [inline app/main.cpp]: remove suffix signal

File: app/main.cpp (hunk 9 above)
Comment (sklencar) [reply app/main.cpp]: List of map layers depends on mapTheme

File: app/main.cpp (hunk 8 above)
Comment (sklencar) [reply app/main.cpp]: reloadDefaultMapThemeSignal and reloadDefaultMapTheme are related (both in AppSettings). Basically the idea is to retrieve name of default map theme and to avoid introducing AppSetting instance to the model therefore the model can be independent.

Same for the retrieving defaultLayer name in layer's model.

The signal suffix or a whole signal name can be replaced though (getDefault* and sendDefault* to keep the relation obvious)

File: app/layersmodel.cpp (hunk 2 above)
Comment (sklencar) [reply app/layersmodel.cpp]: Signal is used in main.qml to update the RecordToolbar. Consider a use case when mapTheme has changed, layers in the layers model have changed, (default/active) index has not changed, but actual layer where the index is pointing at is different from the previous state.

A new signal can be introduced and used for updating the RecordToolbar instead + added docs.

Comment (PeterPetrik) [reply app/layersmodel.cpp]: i would emit only when index is changed, and for the testcase you describe I imaging there is signal in maptheme that is emitted already?

File: app/main.cpp (hunk 8 above)
Comment (PeterPetrik) [reply app/main.cpp]: if you have getDefault* and sendDefault*, why it cannot be one signal that is connected directly here? If you want to send string in argument list, it does not matter, or does it?

File: app/main.cpp (hunk 9 above)
Comment (PeterPetrik) [reply app/main.cpp]: reload means they are really fetched again from data provider? maybe I am just confused with naming.

File: app/layersmodel.h [hunk 11]
```diff
@@ -41,34 +42,44 @@ class LayersModel : public QAbstractListModel
...
     QHash<int, QByteArray> roleNames() const override;
 
     QList<QgsMapLayer *> layers() const;
 
-    int defaultLayerIndex() const;
-    void setDefaultLayerIndex( int index );
+    int activeIndex() const;
+    /**
+     * Sets layer if index is in layers list length range.
+     * @param activeIndex index of the layder from mLayers
```
Comment (PeterPetrik) [inline app/layersmodel.h]: we use "\" notation over "@" in doxy comments

File: app/mapthemesmodel.h [hunk 12]
```diff
@@ -50,16 +53,30 @@ class MapThemesModel : public QAbstractListModel
     QList<QString> mapThemes() const;
     void setMapThemes( const QList<QString> &mapThemes );
 
+    int activeThemeIndex() const;
+    /**
+     * Sets and applies mapTheme if index is in mapThemes list length range.
+     * @param activeThemeIndex index of the theme from the list of themes
```
Comment (PeterPetrik) [inline app/mapthemesmodel.h]: use \ for doxy comments
