### PR TITLE
Fixed RegisterForm after successful registration

### LINKED ISSUE #934: Getting stuck in the Sign up page
Also fix the toast message!

Screenshot_20201015-161355_Input

### PR DESCRIPTION
**Pull request by sklencar**
closes #934

### CODE REVIEW

File: app/merginapi.cpp [hunk 1]
```diff
@@ -826,7 +826,7 @@ void MerginApi::registrationFinished()
     {
       // the self-registration is not allowed on the server
       emit registrationFailed();
-      emit notify( tr( "New registrations are not allowed on the selected Mergin server.%1Please check with your administrator." ).arg( "<br/>" ) );
+      emit notify( tr( "New registrations are not allowed on the selected Mergin server.\n Please check with your administrator." ).arg( "<br/>" ) );
```
Comment (wonder-sk) [inline app/merginapi.cpp:829]: These two changes will break the translations... (and the second one has forgotten `.arg(...)`)
How about we just change the arg(...) content to have `\n` inside?

**Review by wonder-sk — APPROVED** [review]
