### PR TITLE
Bug/settings panel glitches

### LINKED ISSUE #75: Settings panel glitches
- switch to follow GPS on map is very small
- acceptable gps accuracy setting is very small - it is hard to even click the +/- buttons
- acceptable gps accuracy - should show e.g. `3 m` so it is clear the unit is in meters
- GPS accuracy "semaphore"
  - the current state is not highlighted (should highlight the same color as in main panel)
  - the gray color (for "gps off") can be currently hidden as we do not have an option right now to enable/disable GPS

### PR DESCRIPTION
**Pull request by sklencar**
closes #75

### CODE REVIEW

File: app/appsettings.cpp [hunk 1]
```diff
@@ -13,12 +13,14 @@ AppSettings::AppSettings(QObject* parent):QObject(parent)
     QString path = settings.value("defaultProject","").toString();
     QString layer = settings.value("defaultLayer/"  + path,"").toString();
     bool autoCenter = settings.value("autoCenter", false).toBool();
+    int gpsTolerance = settings.value("gpsTolerance", 0).toInt();
```
Comment (wonder-sk) [inline app/appsettings.cpp]: let's use e.g. 10 meters as the default tolerance instead of zero

File: app/qml/NumberSpin.qml [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+    ColorOverlay {
+        anchors.fill: imageDecrease
+        source: imageDecrease
+        color: InputStyle.fontColorBright
+    }
+
+    Text {
+        id: valueText
+        text: value + "m"
```
Comment (wonder-sk) [inline app/qml/NumberSpin.qml]: add a space between the number and the unit

File: app/qml/SettingsPanel.qml [hunk 3]
```diff
@@ -95,80 +95,110 @@ Popup {
...
-
                 }
             }
 
             PanelItem {
-                id: panelItem
                 height: settingsPanel.rowHeight
                 width: parent.width
-                text: qsTr("Acceptable GPS accuracy")
+                text: qsTr("Treshold")
```
Comment (wonder-sk) [inline app/qml/SettingsPanel.qml]: Let's rename to "Accuracy threshold"  (note spelling of threshold)

File: app/qml/SettingsPanel.qml [hunk 4]
```diff
@@ -95,80 +95,110 @@ Popup {
...
+                    }
                 }
             }
 
             PanelItem {
-                id: panelItem1
                 height: settingsPanel.rowHeight
                 width: parent.width
                 color: InputStyle.clrPanelMain
                 text: qsTr("GPS accuracy")
```
Comment (wonder-sk) [inline app/qml/SettingsPanel.qml]: Let's rename to "GPS status"
